### PR TITLE
adding gcsafe pragmas for findOne to work

### PR DESCRIPTION
**Pull request by samsamros**
Adding gcsafe pragma to several procs, including the ones referenced in #28 , this resolves the issue for findOne in #27 , update is still pending testing!

### CODE REVIEW

**Comment by mashingan** [comment]
Can we try to use push-pop pragma? i.e `{.push: gcsafe.}` and `{.pop.}`.
Perhaps it could make the changes easier and simpler.

**Comment by samsamros** [comment]
I was unaware of this use `{.push: gcsafe.}`
I will read more, but I'm happy with a simpler solution than mine :D
I'll do my homework in the meantime. I'll leave the [gcsafedevelop](https://github.com/mashingan/anonimongo/tree/gcsafedevelop) branch just in case, to map the places that needed the pragma

**Comment by mashingan** [comment]
Perfectly fine with both direction, the push-pop pragma or manually adding the `gcsafe` pragma to all functions/procs.
Push-pop pragma is easier but I'm unaware if anything'd break by applying it.
I personally prefer the push-pop pragma direction, but as I said, both perfectly fine for me.
After you decide which is better, you can merge this :+1:

**Comment by inv2004** [comment]
I would vote for non-push/pop because I am a bit afraid of the push/pop solution - theoretically it sounds correct, but, and like you said, - it is more safe to apply the effect to minimum possible code

**Comment by samsamros** [comment]
this is a really good point, and would like to run some tests first. I think this is working with update and findOne, but will try the `{.push.}` pragma. 
I'm guessing we have to exclude templates and then write `{.push.}` again afterwards? 
If this is only affecting a few procs, I would just add the `{.gcsafe.}` to map them, but if this is affecting much more of the code, `{.push.}` seems easier to maintain, but just a guess, because I havent tested yet.

**Comment by mashingan** [comment]
> I'm guessing we have to exclude templates and then write {.push.} again afterwards?

Not sure whether template is safe or not, but if you want to avoid interweaving push-pop when finding templates, you can move the template definitions to above so inside the `{.push gcsafe.}` and `{.pop}` are only procs.

**Comment by samsamros** [comment]
I will test this! So far, with this, find, findOne, and update work fine. So it seems it's only these procs that were causing #27

**Comment by samsamros** [comment]
I've been revewing this, and I think there are very few procs that will cause the compile time error to go off for CRUD procs. I think we should just keep `{.gcsafe.}` for these, and continue to move forward. If more procs require the pragma I think we should continue development with `{.push.}` `{.pop.}`.

If you agree I will continue with the merge. I've been testing 2 weeks on my applications, no errors in compile time have showed up!

**Comment by inv2004** [comment]
@samsamros just merge it. It would not make things worse than we have now :)

**Comment by danbarbarito** [comment]
I just spent an hour trying to figure out why my code wasn't working even though I saw this was fixed in this PR.

For anyone else who is confused, this change has not made it to a new version of the package yet so I had to change my dependencies to reference the HEAD of this Github repo. ie: `requires "https://github.com/mashingan/anonimongo#head"
`

**Comment by samsamros** [comment]
Hi @danbarbarito , the latest version includes these changes. I've faced this issue before, and I've had to uninstall the package with nimble `nimble uninstall anonimongo`, and if I had just compiled the code, Nim caches C code in linux in `${HOME}/.cache/nim/*`. You can safely remove cached C code with `rm`. 
Then you can install with nimble again, and that should get it done.

**Comment by danbarbarito** [comment]
Thank you @samsamros!

**Pull request merged**
